### PR TITLE
Cookie extraction

### LINKED ISSUE #80: Stuck on security check
When logging in, the security check pop-up is not reaching 0, and when trying to log in after the pop-up is gone, it just repeats itself infinitely.

https://github.com/user-attachments/assets/f1585b94-1856-491a-9a9d-e089c6e6a594

I was able to log in on Deezer's official website.

I am using Arch Linux with KDE Plasma. 

This issues persists both on the AUR version of Deezer Enhanced and the AppImage version from the releases of this repository.

I have used this app for a month already with multiple reinstallations, and I had once to wait on this pop-up twice, but it has always worked normally.

I have also tried to use version 1.4.1 from an AppImage, and got the same issue.

I am not sure what have changed, because the same application version on the same PC on the same OS on the same DE with the same installation method was working before. Most likely this is something on the Deezer's side. I would be happy to help in debugging, if it is possible.

I was also trying to use Google for login, and I was receiving this error:

Image

### PR DESCRIPTION
**Pull request by NotQuiteLoona**
Closes #80. Adds a way to extract cookies from several available web browsers, or enter them manually.

### CODE REVIEW

File: src/main/utils/cookies.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+// browsers supported by the library used for extraction
+export const librarySupportedBrowsers: Map<string, string> = new Map<
```
Comment (duzda) [inline src/main/utils/cookies.ts]:
```
import { BrowserName } from '@steipete/sweet-cookie';
export const LIBRARY_SUPPORTED_BROWSERS: ReadOnly<Record<BrowserName, string>> = {
  chrome: 'Google Chrome',
  ...
}
```

It's helpful to use `ReadOnly` for objects, as `const` means immutable reference or simple value, not immutable object. As `Map<string, string>` goes, in this case it's better to go with `Record<BrowserName, ...>`, this type is exhaustive, in case the library changes it's underlying type, it won't let us compile. In general `Map` is not the most often used type in TS.

File: src/main/cookies.ts [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+  });
+
+  ipcMain.handle(
+    COOKIES_GET_FROM_BROWSER,
+    async (_, browserId: string): Promise<string> => {
+      if (librarySupportedBrowsers.has(browserId)) {
+        const { cookies, warnings } = await getCookies({
+          url: DEEZER_URL,
+          names: [ARL_COOKIE_NAME],
+          // @ts-expect-error this array requires a BrowserName, but BrowserName is a union of strings.
```
Comment (duzda) [inline src/main/cookies.ts]: This is unnecessary.

File: src/main/cookies.ts [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+      }
+
+      // TODO: other browsers can be handled there
+      switch (browserId) {
+        default:
+          return '';
+      }
+    }
+  );
+};
```
Comment (duzda) [inline src/main/cookies.ts]: newline after here please

File: src/renderer/pages/CookieSetupPage.tsx [hunk 4]
```diff
@@ -0,0 +1,144 @@
...
+        window.renderer.cookieAPI.setArl(arl);
+        setCookiesExist(true);
+      });
+  };
+  return (
+    <main>
+      <div className="flex flex-row">
+        <div className="min-w-96 w-4/5 mx-auto my-8 flex flex-col gap-8 bg-base-200 p-8 rounded-md border-2 border-neutral">
+          <p>
+            Deezer utilizes complicated cryptographical checks during login,
```
Comment (duzda) [inline src/renderer/pages/CookieSetupPage.tsx]:
```
Deezer utilizes complicated cryptographic checks during login,
```

cryptographical is not an English word? (I'm surprised as well)

File: src/renderer/pages/CookieSetupPage.tsx [hunk 5]
```diff
@@ -0,0 +1,144 @@
...
+            'text-neutral-600',
+            'text-error'
+          );
+          span.textContent = `${arl}`;
+          return;
+        }
+
+        window.renderer.cookieAPI.setArl(arl);
+        setCookiesExist(true);
+      });
```
Comment (duzda) [inline src/renderer/pages/CookieSetupPage.tsx]: Prefer modern syntax

```ts
const getArlFromBrowser = async (browserId: string) => {
  const arl = await window.renderer.cookieAPI.getCookieFromBrowser(browserId);
  ... // Do stuff with arl instead of then chaining
}
```

File: src/renderer/pages/CookieSetupPage.tsx [hunk 6]
```diff
@@ -0,0 +1,144 @@
...
+      setCookiesExist(await window.renderer.cookieAPI.getCookieStatus());
+    };
+
+    // noinspection JSIgnoredPromiseFromCall
+    findCookies();
+  }, [setCookiesExist]);
+
+  const cookieInputRef = useRef<HTMLInputElement>(null);
+  const browserListSelectionRef = useRef<HTMLSelectElement>(null);
+  const extractionStatusSpanRef = useRef<HTMLSpanElement>(null);
```
Comment (duzda) [inline src/renderer/pages/CookieSetupPage.tsx]: Please see: https://react.dev/reference/react-dom/components/input#controlling-an-input-with-a-state-variable on how to manage state.

File: src/renderer/pages/CookieSetupPage.tsx [hunk 7]
```diff
@@ -0,0 +1,144 @@
...
+
+                <button
+                  type="button"
+                  className="rounded-md p-2 ml-3 cursor-pointer w-40 font-bold text-primary"
+                  style={{ background: cookiesExist ? '#b769ff' : '#a13bff' }}
+                  disabled={cookiesExist}
+                  onClick={() => {
+                    // @ts-expect-error we don't need to await this method, as it can't be done on the client.
+                    getArlFromBrowser(browserListSelectionRef.current.value);
+                  }}
```
[the remark this answers is not in the document]
Comment (NotQuiteLoona) [reply src/renderer/pages/CookieSetupPage.tsx]: I could barely remember that it was showing me an error in the console. I'll check again in my IDE, when I'll deal with Git history.

**Comment by duzda** [comment]
> Oh, no problem, of course! I hope everything is good for you.

Of course, it's just getting more and more difficult to find time for side projects

> Okay, going to read Git documentation now, for the first time in my life (all my Git knowledge goes from a Russian IT news website where I was moderately active years ago, sorry 😅).

No worries, I think no one really knows `git` and honestly, messing up is the best way to learn.

> Hm, I seemingly checked indentation, and prettier seemed to not show anything.

Prettier doesn't care about newlines, I do however.

File: src/renderer/components/Cookies/CookieButton.tsx [hunk 8]
```diff
@@ -0,0 +1,45 @@
...
+        focusable="false"
+        height="18"
+        width="18"
+        viewBox="0 0 24 24"
+        className={svgClass}
+      >
+        <path d="M480-80q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-75 29-147t81-128.5q52-56.5 125-91T475-881q21 0 43 2t45 7q-9 45 6 85t45 66.5q30 26.5 71.5 36.5t85.5-5q-26 59 7.5 113t99.5 56q1 11 1.5 20.5t.5 20.5q0 82-31.5 154.5t-85.5 127q-54 54.5-127 86T480-80Zm-60-480q25 0 42.5-17.5T480-620q0-25-17.5-42.5T420-680q-25 0-42.5 17.5T360-620q0 25 17.5 42.5T420-560Zm-80 200q25 0 42.5-17.5T400-420q0-25-17.5-42.5T340-480q-25 0-42.5 17.5T280-420q0 25 17.5 42.5T340-360Zm260 40q17 0 28.5-11.5T640-360q0-17-11.5-28.5T600-400q-17 0-28.5 11.5T560-360q0 17 11.5 28.5T600-320ZM480-160q122 0 216.5-84T800-458q-50-22-78.5-60T683-603q-77-11-132-66t-68-132q-80-2-140.5 29t-101 79.5Q201-644 180.5-587T160-480q0 133 93.5 226.5T480-160Zm0-324Z">
+          {' '}
+        </path>
+      </svg> */}
```
[the remark this answers is not in the document]
Comment (duzda) [reply src/renderer/components/Cookies/CookieButton.tsx]: Agreed

**Comment by NotQuiteLoona** [comment]
> I think in this case you wanted to do something like:
> 
> ```git
> git reset HEAD~2
> ```
> 
> to rollback the last two commit.
> 
> with `git rebase -i` you could do:
> 
> ```
> git rebase -i HEAD~10
> 
> (find the duplicate commit in the list, change pick to t, make sure to not delete other lines!!!)
> t 567bb6a # refactor: removing the cookie removal functionality (didn't work anyway for some reason) and various UI adjustments
> ```
> 
> t stands for reset.

Thanks a lot! I'll know what to do next time. This time I've just reset to the commit ID and did a force push. 

> Yes, please whatever you do, make sure you work safely and do not loose the changes, we can figure out git stuff as the last part.

Yep, there is nothing lost now, and I'll be more attentive in the future. 

> Btw, if you'd prefer instant messaging, please add me on Discord, [duzda](https://discord.com/users/351338895658582016).

Okay!

File: src/preload.ts [hunk 9]
```diff
@@ -73,11 +83,36 @@ export const themesAPI = {
...
+    ipcRenderer.send(LOGIN_NAVIGATE_TO_DEEZER_LOGIN_PAGE);
+  },
+  setActionOnLoginCookieAdded: (callback: () => void) => {
+    ipcRenderer.send(LOGIN_SET_HANDLER_ON_LOGIN);
+    ipcRenderer.once(LOGIN_ON_LOGIN_COOKIE_ADDED, () => callback());
+  },
+  setActionOnLoginCookieRemoved: (callback: () => void) => {
+    ipcRenderer.send(LOGIN_SET_HANDLER_ON_LOGOUT);
+    ipcRenderer.once(LOGIN_ON_LOGIN_COOKIE_REMOVED, () => callback());
+  },
```
Comment (duzda) [inline src/preload.ts]: I think you don't need these two events.

File: src/main/login.ts [hunk 10]
```diff
@@ -0,0 +1,71 @@
...
+      'changed',
+      (_e, cookie, _c, removed) => {
+        if (cookie.name !== ARL_COOKIE_NAME) return;
+
+        if (removed) {
+          toolbarView.webContents.send(LOGIN_ON_LOGIN_COOKIE_REMOVED);
+        }
+      }
+    );
+  });
```
Comment (duzda) [inline src/main/login.ts]: Squash

**Comment by lm41** [comment]
Hello, I just wanted to check with you if this PR is ready for testing and/or if anything else needs to be added.
